spring:
  redis:
    host: 175.27.230.182
    port: 6379
    password: test123
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0
